name: Actualizar Referencias Científicas

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1'  # Lunes a las 14:00 UTC = 9:00 AM Cuba

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install requests

      - name: Ejecutar script
        env:
          REDMINE_API_KEY: ${{ secrets.REDMINE_API_KEY }}
        run: |
          python main.py
